### ISSUE TITLE
The number of required GPUs exceeds the total number of available GPUs in the cluster

### ISSUE THREAD

**Issue by SonicEver** [imoneoi/openchat#117]
nvidia-smi
Fri Dec  8 09:36:24 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.04              Driver Version: 546.17       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
|  0%   34C    P8              29W / 450W |     22MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4060 Ti     On  | 00000000:0C:00.0 Off |                  N/A |
|  0%   29C    P8               6W / 165W |      0MiB / 16380MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        23      G   /Xwayland                                 N/A      |
|    1   N/A  N/A        23      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+

Full error info:

python -m ochat.serving.openai_api_server --model /mnt/d/tools/ai/openchat/openchat_3.5 --engine-use-ray --worker-use-ray --tensor-parallel-size 2
FlashAttention not found. Install it if you need to train models.
FlashAttention not found. Install it if you need to train models.
2023-12-08 10:19:36,125 INFO worker.py:1673 -- Started a local Ray instance.
(pid=32221) FlashAttention not found. Install it if you need to train models.
(pid=32221) FlashAttention not found. Install it if you need to train models.
2023-12-08 10:19:37,662 INFO worker.py:1507 -- Calling ray.init() again after it has already been called.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sonicx/miniconda3/envs/openchat/lib/python3.11/site-packages/ochat/serving/openai_api_server.py", line 368, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sonicx/miniconda3/envs/openchat/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 492, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
                                               ^^^^^^^^^^^^^^^^^^^
  File "/home/sonicx/miniconda3/envs/openchat/lib/python3.11/site-packages/vllm/engine/ray_utils.py", line 106, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
(AsyncTokenizer pid=32221) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

**Comment by FabrizioRicciarelli** [comment]
Still problematic... any resolution?
