### ISSUE TITLE
RecursionError on OpenAi python client inside a docker container

### ISSUE THREAD

**Issue by GaetanBaert** [imoneoi/openchat#126]
Hello, 

My code worked well on native configuration, but I got these traceback in a docker container : 

```
2023-12-13 17:25:46 Traceback (most recent call last):
2023-12-13 17:25:46   File "main.py", line 59, in <module>
2023-12-13 17:25:46     openai_client = OpenAI(api_key="<myAPIkey>" ,base_url="http://<openchat_server_url>/v1")
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/openai/_client.py", line 106, in __init__
2023-12-13 17:25:46     super().__init__(
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/openai/_base_client.py", line 758, in __init__
2023-12-13 17:25:46     self._client = http_client or SyncHttpxClientWrapper(
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 672, in __init__
2023-12-13 17:25:46     self._transport = self._init_transport(
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 720, in _init_transport
2023-12-13 17:25:46     return HTTPTransport(
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 133, in __init__
2023-12-13 17:25:46     ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 51, in create_ssl_context
2023-12-13 17:25:46     return SSLConfig(
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 75, in __init__
2023-12-13 17:25:46     self.ssl_context = self.load_ssl_context()
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 87, in load_ssl_context
2023-12-13 17:25:46     return self.load_ssl_context_verify()
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 124, in load_ssl_context_verify
2023-12-13 17:25:46     context = self._create_default_ssl_context()
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 161, in _create_default_ssl_context
2023-12-13 17:25:46     set_minimum_tls_version_1_2(context)
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/httpx/_compat.py", line 28, in set_minimum_tls_version_1_2
2023-12-13 17:25:46     context.minimum_version = ssl.TLSVersion.TLSv1_2
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/site-packages/eventlet/green/ssl.py", line 476, in minimum_version
2023-12-13 17:25:46     super(_original_sslcontext, _original_sslcontext).minimum_version.__set__(self, value)
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/ssl.py", line 586, in minimum_version
2023-12-13 17:25:46     super(SSLContext, SSLContext).minimum_version.__set__(self, value)
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/ssl.py", line 586, in minimum_version
2023-12-13 17:25:46     super(SSLContext, SSLContext).minimum_version.__set__(self, value)
2023-12-13 17:25:46   File "/usr/local/lib/python3.8/ssl.py", line 586, in minimum_version
2023-12-13 17:25:46     super(SSLContext, SSLContext).minimum_version.__set__(self, value)
2023-12-13 17:25:46   [Previous line repeated 488 more times]
2023-12-13 17:25:46 RecursionError: maximum recursion depth exceeded
```

I'm not sure if it is an OpenAI or openchat related issue, but maybe SSL verification can cause some troubles ? I tried to use `openai.verify_ssl_certs=False` but it didn't change anything...

**Comment by GaetanBaert** [comment]
I found what was wrong : it seems eventlet was installed on the docker and not on native configuration. Removing it from the docker requirements solved the problem.
