### ISSUE TITLE
"Getting requirements to build wheel did not run successfully" 

### ISSUE THREAD

**Issue by mkloppel** [imoneoi/openchat#142]
Any help would be greatly appreciated. I have given up after hours of frustration, I can't keep going. I am sure its my fault somehow but I just can't see what I am doing wrong. If you need info, just let me know.

**OS**: Windows 10
**Paths**: Cuda is in the paths (2 x actually)

- I have:

1. Installed numpy (Both python and conda)
2. I updated conda 
3. I updated pip
4. Installed Cuda Toolkit 12.1
5. Run the command outside of the conda environment recommended and inside of the environment.
6.  Ran ```pip3 install --no-cache-dir ochat``` to not use cached packages
7. I installed pytorch 11.8 & 12.1 to match the cuda toolkit at different times  

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

```
ochat>pip list
Package            Version
------------------ ------------
certifi            2023.11.17
charset-normalizer 3.3.2
filelock           3.9.0
fsspec             2023.4.0
idna               3.6
Jinja2             3.1.2
MarkupSafe         2.1.3
mkl-fft            1.3.8
mkl-random         1.2.4
mkl-service        2.4.0
mpmath             1.3.0
networkx           3.0
numpy              1.26.2
Pillow             9.3.0
pip                23.3.2
requests           2.31.0
setuptools         68.2.2
sympy              1.12
torch              2.1.2+cu121
torchaudio         2.1.2+cu121
torchvision        0.16.2+cu121
typing_extensions  4.4.0
urllib3            2.1.0
wheel              0.41.2
```

```
ochat>conda list
# packages in environment at C:\Users\mklop\anaconda3\envs\openchat:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bzip2                     1.0.8                he774522_0
ca-certificates           2023.12.12           haa95532_0
filelock                  3.9.0                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
jinja2                    3.1.2                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
markupsafe                2.1.3                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0           py311h2bbff1b_1
mkl_fft                   1.3.8           py311h2bbff1b_0
mkl_random                1.2.4           py311h59b6b97_0
mpmath                    1.3.0                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
numpy                     1.26.2          py311hdab7c0b_0
numpy-base                1.26.2          py311hd01c5d8_0
openssl                   3.0.12               h2bbff1b_0
pillow                    9.3.0                    pypi_0    pypi
pip                       23.3.2                   pypi_0    pypi
python                    3.11.5               he1021f5_0
setuptools                68.2.2          py311haa95532_0
sqlite                    3.41.2               h2bbff1b_0
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
tk                        8.6.12               h2bbff1b_0
torch                     2.1.2+cu121              pypi_0    pypi
torchaudio                2.1.2+cu121              pypi_0    pypi
torchvision               0.16.2+cu121             pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2          py311haa95532_0
xz                        5.4.5                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0
```

```
Collecting vllm (from ochat)
  Using cached vllm-0.2.6.tar.gz (167 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      C:\Users\mklop\AppData\Local\Temp\pip-build-env-oo29vnnj\overlay\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
      Traceback (most recent call last):
        File "C:\Users\mklop\anaconda3\envs\openchat\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mklop\anaconda3\envs\openchat\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mklop\anaconda3\envs\openchat\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mklop\AppData\Local\Temp\pip-build-env-oo29vnnj\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mklop\AppData\Local\Temp\pip-build-env-oo29vnnj\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\mklop\AppData\Local\Temp\pip-build-env-oo29vnnj\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 298, in <module>
        File "<string>", line 268, in get_vllm_version
      NameError: name 'nvcc_cuda_version' is not defined. Did you mean: 'cuda_version'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by deadpipe** [comment]
Facing same issue here. Have you found a solution, @mkloppel ?
