### ISSUE TITLE
docker gets  undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by hanselke** [imoneoi/openchat#47]
`openchat-openchat-server-1  | Traceback (most recent call last):
openchat-openchat-server-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
openchat-openchat-server-1  |     return _run_code(code, main_globals, None,
openchat-openchat-server-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
openchat-openchat-server-1  |     exec(code, run_globals)
openchat-openchat-server-1  |   File "/ochat/serving/openai_api_server.py", line 29, in <module>
openchat-openchat-server-1  |     from ochat.config.model_config import MODEL_CONFIG_MAP
openchat-openchat-server-1  |   File "/ochat/config/model_config.py", line 7, in <module>
openchat-openchat-server-1  |     import ochat.models
openchat-openchat-server-1  |   File "/ochat/models/__init__.py", line 1, in <module>
openchat-openchat-server-1  |     from ochat.models.unpadded_llama import LlamaForCausalLM
openchat-openchat-server-1  |   File "/ochat/models/unpadded_llama.py", line 31, in <module>
openchat-openchat-server-1  |     from transformers.modeling_utils import PreTrainedModel
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 88, in <module>
openchat-openchat-server-1  |     from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
openchat-openchat-server-1  |     from .accelerator import Accelerator
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 35, in <module>
openchat-openchat-server-1  |     from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in <module>
openchat-openchat-server-1  |     from .utils import (
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py", line 136, in <module>
openchat-openchat-server-1  |     from .launch import (
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/launch.py", line 33, in <module>
openchat-openchat-server-1  |     from ..utils.other import is_port_in_use, merge_dicts
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 27, in <module>
openchat-openchat-server-1  |     from .transformer_engine import convert_model
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
openchat-openchat-server-1  |     import transformer_engine.pytorch as te
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
openchat-openchat-server-1  |     from .module import LayerNormLinear
openchat-openchat-server-1  |   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module.py", line 20, in <module>
openchat-openchat-server-1  |     import transformer_engine_extensions as tex
openchat-openchat-server-1  | ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

seems like there is some sort of cuda version error?

**Comment by alcanuns** [comment]
any updates? having the same error :(

**Comment by blap** [comment]
To avoid this error I first install the respective python-dev (`sudo apt-get install python3.10-dev` for python3.10) and install flash-attn with `MAX_JOBS=4 pip3 install --no-build-isolation "flash-attn<2"`. #41
