### ISSUE TITLE
Installing openchat on MacOS

### ISSUE THREAD

**Issue by erima2020** [imoneoi/openchat#65]
Hello,
I'm trying to install openchat on MacOS on a MacStudio with M1Ultra. Through pip install (option 1) and the compile option (option 3), I get an error "building the wheel" following the lack of CUDA, which is mentioned is required for compilation. Could you provide installation instructions for MacOS?
Best wishes,
Eric

**Comment by maxim-saplin** [comment]
@imoneoi , looking forward to updates! Also wanted to try out the model, yet failed to install it on M1 MacBook Pro. Since there's no CUDA on Mac, does it mean there's no way to run openchat there?

**Comment by tsenti-city** [comment]
Facing the same issue on Macbook Pro.  Everything appears to be in place but I am receiving this error when trying to install ochat (see cant find CUDA at bottom.   Thought it was a numpy issue at first but that is installed and verified to be working)

Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /private/var/folders/p9/226979954w5862dr608ydrg80000gn/T/pip-build-env-o_dgxoio/overlay/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/Users/thadsenti/anaconda3/envs/openchat/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/thadsenti/anaconda3/envs/openchat/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/thadsenti/anaconda3/envs/openchat/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/p9/226979954w5862dr608ydrg80000gn/T/pip-build-env-o_dgxoio/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/p9/226979954w5862dr608ydrg80000gn/T/pip-build-env-o_dgxoio/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/p9/226979954w5862dr608ydrg80000gn/T/pip-build-env-o_dgxoio/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
      RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.
      [end of output]

**Comment by tsenti-city** [comment]
I dont think it's possible as the new M1's use the "Metal" framework to interact with Apple's GPU's.     Unless there is a way to get these libraries to just NOT use a GPU....

**Comment by Marviel** [comment]
https://github.com/vllm-project/vllm/pull/1028

**Comment by Marviel** [comment]
> [vllm-project/vllm#1028](https://github.com/vllm-project/vllm/pull/1028)

It looks like VLLM (upstream dependency) is about to add in a "CPU-ONLY" mode, which would unblock this
